name: OpenROAD Flow For SKY130

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  openroad:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget

      - name: Download and install OpenROAD .deb
        run: |
          wget https://github.com/Precision-Innovations/OpenROAD/releases/download/2024-12-14/openroad_2.0-17598-ga008522d8_amd64-ubuntu-22.04.deb -O openroad.deb
          sudo apt-get install -y ./openroad.deb
          openroad -version

      - name: Clone OpenROAD-flow-scripts
        run: |
          git clone --depth=1 https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts.git

      - name: Copy user design
        run: |
          mkdir -p OpenROAD-flow-scripts/flow/designs/src/cm0ikmcu
          mkdir -p OpenROAD-flow-scripts/flow/designs/sky130hd/cm0ikmcu
          cp -r designs/cm0ikmcu/src/*.v OpenROAD-flow-scripts/flow/designs/src/cm0ikmcu/
          cp designs/cm0ikmcu/rules-base.json OpenROAD-flow-scripts/flow/designs/sky130hd/cm0ikmcu/
          cp designs/cm0ikmcu/config.mk OpenROAD-flow-scripts/flow/designs/sky130hd/cm0ikmcu/
          cp designs/cm0ikmcu/constraint.sdc OpenROAD-flow-scripts/flow/designs/sky130hd/cm0ikmcu/

      - name: Run OpenROAD Flow
        run: |
          cd OpenROAD-flow-scripts/flow
          make DESIGN_CONFIG=./designs/sky130hd/cm0ikmcu/config.mk

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: openroad-results
          path: OpenROAD-flow-scripts/flow/results/sky130hd/cm0ikmcu
