name: OpenROAD Flow For SKY130

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  openroad:
    runs-on: ubuntu-22.04
    container:
      image: appaapps/openroad:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone OpenROAD-flow-scripts
        run: |
          git clone --depth=1 https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts.git
          cd OpenROAD-flow-scripts
          ./etc/DependencyInstaller.sh -base -constant-build-dir && ./etc/DependencyInstaller.sh -common -constant-build-dir
          ./build_openroad.sh --threads 16 > build.log 2>&1 || (cat build.log && exit 1)

      - name: Copy user design
        run: |
          mkdir -p OpenROAD-flow-scripts/flow/designs/src/cm0ikmcu
          mkdir -p OpenROAD-flow-scripts/flow/designs/sky130hd/cm0ikmcu
          cp -r designs/cm0ikmcu/src/*.v OpenROAD-flow-scripts/flow/designs/src/cm0ikmcu/
          cp designs/cm0ikmcu/rules-base.json OpenROAD-flow-scripts/flow/designs/sky130hd/cm0ikmcu/
          cp designs/cm0ikmcu/config.mk OpenROAD-flow-scripts/flow/designs/sky130hd/cm0ikmcu/
          cp designs/cm0ikmcu/constraint.sdc OpenROAD-flow-scripts/flow/designs/sky130hd/cm0ikmcu/

      - name: Run OpenROAD Flow
        run: |
          cd OpenROAD-flow-scripts/flow
          make DESIGN_CONFIG=./designs/sky130hd/cm0ikmcu/config.mk

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: openroad-results
          path: OpenROAD-flow-scripts/flow/results/sky130hd/cm0ikmcu
