name: OpenROAD Flow For SKY130

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  openroad:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y \
          cmake \
          swig \
          tcl-dev \
          libboost-all-dev \
          libeigen3-dev \
          flex bison \
          libspdlog-dev \
          libgtest-dev \
          python3 python3-pip \
          time

      - name: Extract prebuilt OpenROAD
        run: |
          mkdir -p $HOME/openroad
          tar -xzf tools/openroad.tar.gz -C $HOME/openroad
          echo "$HOME/openroad/bin" >> $GITHUB_PATH

      - name: Verify OpenROAD
        run: |
          openroad -version

      - name: Clone OpenROAD-flow-scripts
        run: |
          git clone --depth=1 https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts.git
          cd OpenROAD-flow-scripts

      - name: Copy user design
        run: |
          mkdir -p OpenROAD-flow-scripts/flow/designs/src/cm0ikmcu
          mkdir -p OpenROAD-flow-scripts/flow/designs/src/cm0ikmcu/core
          mkdir -p OpenROAD-flow-scripts/flow/designs/src/cm0ikmcu/dap
          mkdir -p OpenROAD-flow-scripts/flow/designs/src/cm0ikmcu/ualdis
          mkdir -p OpenROAD-flow-scripts/flow/designs/sky130hd/cm0ikmcu
          cp -r designs/cm0ikmcu/src/*.v OpenROAD-flow-scripts/flow/designs/src/cm0ikmcu/
          cp -r designs/cm0ikmcu/src/core/*.v OpenROAD-flow-scripts/flow/designs/src/cm0ikmcu/core
          cp -r designs/cm0ikmcu/src/dap/*.v OpenROAD-flow-scripts/flow/designs/src/cm0ikmcu/dap
          cp -r designs/cm0ikmcu/src/ualdis/*.v OpenROAD-flow-scripts/flow/designs/src/cm0ikmcu/ualdis
          ls OpenROAD-flow-scripts/flow/designs/src/cm0ikmcu/
          cp designs/cm0ikmcu/rules-base.json OpenROAD-flow-scripts/flow/designs/sky130hd/cm0ikmcu/
          cp designs/cm0ikmcu/config.mk OpenROAD-flow-scripts/flow/designs/sky130hd/cm0ikmcu/
          cp designs/cm0ikmcu/constraint.sdc OpenROAD-flow-scripts/flow/designs/sky130hd/cm0ikmcu/
          
      - name: Run OpenROAD Flow
        run: |
          pip3 install pyyaml
          export OPENROAD_EXE=/usr/bin/openroad
          export YOSYS_EXE=/usr/bin/yosys
          cd OpenROAD-flow-scripts/flow
          make DESIGN_CONFIG=./designs/sky130hd/cm0ikmcu/config.mk

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: openroad-results
          path: OpenROAD-flow-scripts/flow/results/sky130hd/cm0ikmcu
